### Запуск приложения
GET http://localhost:8080

### Информация о приложении
GET http://localhost:8080/info

### Получение списка всех рецептов
GET http://localhost:8080/recipe

### Получение нужного рецепта из списка по id
GET http://localhost:8080/recipe/0

### Создание нового рецепта 1
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "recipeName": "Сырники из творога",
  "preparingTime": 30,
  "ingredients": [
    {"ingredientName": "Творог",
      "amount": 350,
      "unit": "грамм"},
    {"ingredientName": "Куриное яйцо",
      "amount": 2,
      "unit": "шт."},
    {"ingredientName": "Пшеничная мука",
      "amount": 6,
      "unit": "ст.л."},
    {"ingredientName": "Сахар",
      "amount": 2,
      "unit": "ст.л."}],

  "cookingSteps":
  [ "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте.",
    "Всыпьте в творог муку и тщательно перемешайте.",
    "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
    "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.",
    "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния.",
    "Повторяйте, пока творог не закончится."
  ]
}

### Создание нового рецепта 2
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "recipeName": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "preparingTime": 7,
  "ingredients": [
    {"ingredientName": "Специи",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Консервированная фасоль",
      "amount": 400,
      "unit": "грамм"},
    {"ingredientName": "Лимон",
      "amount": 1,
      "unit": "шт."},
    {"ingredientName": "Чеснок",
      "amount": 2,
      "unit": "зубчика"},
    {"ingredientName": "Оливковое масло",
      "amount": 50,
      "unit": "мл."},
    {"ingredientName": "Рукола",
      "amount": 100,
      "unit": "грамм"},
    {"ingredientName": "Творожный сыр",
      "amount": 200,
      "unit": "грамм"},
    {"ingredientName": "Красный лук",
      "amount": 50,
      "unit": "грамм"}],

  "cookingSteps": [
    "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой.",
    "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром.",
    "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."]
}

### Создание нового рецепта 3
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "recipeName": "Чечевичный суп с мятой",
  "preparingTime": 30,
  "ingredients": [
    {"ingredientName": "Красная чечевица",
      "amount": 150,
      "unit": "грамм"},
    {"ingredientName": "Репчатый лук",
      "amount": 1,
      "unit": "головка"},
    {"ingredientName": "Морковь",
      "amount": 1,
      "unit": "шт."},
    {"ingredientName": "Подсолнечное масло",
      "amount": 30,
      "unit": "мл."},
    {"ingredientName": "Сливочное масло",
      "amount": 15,
      "unit": "гр."},
    {"ingredientName": "Пшеничная мука",
      "amount": 30,
      "unit": "гр."},
    {"ingredientName": "Сливки 33%",
      "amount": 50,
      "unit": "мл."},
    {"ingredientName": "Специи",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Лимон",
      "amount": 1,
      "unit": "шт."},
    {"ingredientName": "Мята",
      "amount": 0,
      "unit": "по вкусу"}],

  "cookingSteps": [
    "В небольшую кастрюлю налить литр воды и засыпать промытую чечевицу. Поставить кастрюлю на средний огонь.",
    "Натереть небольшую морковь на крупной терке, мелко нарезать лук. Как только чечевица начнет кипеть, надо убавить огонь, а затем долить еще 200 мл воды или бульона. Варить еще десять минут.",
    "Разогреть широкую плоскую сковороду, добавить туда подсолнечное и сливочное масло. Обжарить лук и морковь.",
    "Добавить обжаренные овощи в кастрюлю, влить сливки. Взбить суп ручным блендером, чтобы он превратился в густое пюре. Суп можно подавать к столу."]
}

### Создание нового рецепта 4
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "recipeName": "Салат с креветками и кунжутом",
  "preparingTime": 20,
  "ingredients": [
    {"ingredientName": "Помидоры",
      "amount": 3,
      "unit": "шт."},
    {"ingredientName": "Королевские креветки",
      "amount": 300,
      "unit": "гр."},
    {"ingredientName": "Зеленый салат",
      "amount": 1,
      "unit": "пучок"},
    {"ingredientName": "Огурцы",
      "amount": 2,
      "unit": "шт."},
    {"ingredientName": "Специи",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Майонез",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Кунжутные семечки",
      "amount": 3,
      "unit": "ст.л."}],

  "cookingSteps": [
    "Порезать овощи крупно, салат порвать на куски.",
    "Довести до кипения сильно соленую воду и добавить креветки. После кипения варить 5 минут. Очистить креветки от панциря.",
    "Смешать овощи и креветки. Посыпать кунжутными семечками и заправить майонезом."]
}

### Создание нового рецепта 5
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "recipeName": "Творожные пончики в сахарной пудре",
  "preparingTime": 30,
  "ingredients": [
    {"ingredientName": "Творог",
      "amount": 250,
      "unit": "грамм"},
    {"ingredientName": "Куриное яйцо",
      "amount": 3,
      "unit": "шт."},
    {"ingredientName": "Пшеничная мука",
      "amount": 8,
      "unit": "ст.л."},
    {"ingredientName": "Сахар и соль",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Оливковое масло",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Сода",
      "amount": 1,
      "unit": "ч.л."},
    {"ingredientName": "Сахарная пудра с ванилью",
      "amount": 0,
      "unit": "по вкусу"}],

  "cookingSteps": [
    "В миске смешать творог, яйца, муку, сахар, соду и соль до однородной консистенции.",
    "В небольшом сотейнике оливковое масло хорошо разогреть.",
    "При помощи чайной ложки или руками скатать из теста шарики, каждый размером чуть меньше грецкого ореха.",
    "Бросить пончики в кипящее масло и жарить на небольшом огне, постоянно переворачивая шумовкой.",
    "Готовые пончики выложить на бумажное полотенце и оставить на одну-две минуты — чтобы оно впитало лишнее масло. ",
    "Подавать пончики горячими, выложив на блюдо и посыпав сахарной пудрой, смешанной с ванилином."]
}

### Редактирование рецепта
PUT http://localhost:8080/recipe/0
Content-Type: application/json

{
  "recipeName": "Творожные пончики в сахарной пудре test",
  "preparingTime": 25,
  "ingredients": [
    {"ingredientName": "Творог",
      "amount": 250,
      "unit": "грамм"},
    {"ingredientName": "Куриное яйцо",
      "amount": 3,
      "unit": "шт."},
    {"ingredientName": "Пшеничная мука",
      "amount": 8,
      "unit": "ст.л."},
    {"ingredientName": "Сахар и соль",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Оливковое масло",
      "amount": 0,
      "unit": "по вкусу"},
    {"ingredientName": "Сода",
      "amount": 0.5,
      "unit": "ч.л."},
    {"ingredientName": "Сахарная пудра с ванилью",
      "amount": 0,
      "unit": "по вкусу"}],

  "cookingSteps": [
    "В миске смешать творог, яйца, муку, сахар, соду и соль до однородной консистенции.",
    "В небольшом сотейнике оливковое масло хорошо разогреть.",
    "При помощи чайной ложки или руками скатать из теста шарики, каждый размером чуть меньше грецкого ореха.",
    "Бросить пончики в кипящее масло и жарить на небольшом огне, постоянно переворачивая шумовкой.",
    "Готовые пончики выложить на бумажное полотенце и оставить на одну-две минуты — чтобы оно впитало лишнее масло. ",
    "Подавать пончики горячими, выложив на блюдо и посыпав сахарной пудрой, смешанной с ванилином."]
}

### Удаление рецепта
DELETE http://localhost:8080/recipe/0

### Скачивание всех рецептов в Json-файле
GET http://localhost:8080/recipe/download

### Импорт Json-файла
POST http://localhost:8080/recipe/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="recipes"; filename="importRecipes.json"
Content-Type: application/json

< ./importRecipes.json
--WebAppBoundary--

### Скачивание всех рецептов
GET http://localhost:8080/recipe/export
